trigger:
  branches:
    include:
      - dev
      - uat
      - prod

stages:
  - stage: Build
    jobs:
      - job: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              command: buildAndPush
              repository: $(dockerRegistryServiceConnection)/myapp
              dockerfile: Dockerfile
              tags: $(Build.BuildId)

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              kubectl apply -f k8s/dev-deployment.yaml
            displayName: Deploy to Dev
        environment: dev

      - job: DeployToUAT
        dependsOn: DeployToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              kubectl apply -f k8s/uat-deployment.yaml
            displayName: Deploy to UAT
        environment: uat

      - job: DeployToProd
        dependsOn: DeployToUAT
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              kubectl apply -f k8s/prod-deployment.yaml
            displayName: Deploy to Prod
        environment: prod
